config/routes.rb
Rails.application.routes.draw do
  get 'mypages/show'
  devise_scope :user do
    get 'users/sign_in', to: 'sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'sessions#create', as: :user_session
    get 'users/sign_out', to: 'sessions#destroy', as: :destroy_user_session
    get 'users/sign_up', to: 'registrations#new', as: :new_user_registration
    post 'users/sign_up', to: 'registrations#create', as: :user_registration
    get 'registrations/edit', to: 'registrations#edit', as: :edit_user_registration
    patch 'registrations/update', to: 'registrations#update', as: :update_user_registration
  end
  root to: 'items#index'
  get 'items/:id/cheackout', to: 'items#cheackout', as: 'item_cheackout'
  resources :items do
    resources :chats, only: [:create]
    member do
      get :checkout
    end
  end
  resources :messages
  resources :mypages do
    member do
      get :purchased_items
      get :listed_items
    end
  end

  get 'secondaddress/edit_or_new', to: 'secondaddresses#edit_or_new', as: 'edit_or_new_secondaddress'
  resources :secondaddresses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :item
  has_many :messages
end

app/models/image.rb
class Image < ApplicationRecord
  # Active Storageに切り替えるため使用しません
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
  has_one_attached :image
  has_many :chats
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/mypage.rb
class Mypage < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/secondaddress.rb
class Secondaddress < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :items, through: :orders
  has_many :image
  has_many :messages
  has_secure_password
  validates :email, uniqueness: true
  has_one :mypage
  has_one :secondaddress

  #仮想属性をユーザーモデルに追加
  attr_accessor :new_password, :new_password_confirmation, :current_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Devise::Controllers::Helpers

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

  def require_login
    unless logged_in?
      redirect_to new_user_session_path
    end
  end

  def logged_in?
    session[:user_id].present?
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_item
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_login

  def index
    @items = Item.where(buyer_id: nil).where.not(seller_id: current_user.id)
  end

  def show
    @item = Item.find(params[:id])
    @chat = Chat.find_by(item_id: @item.id)
    @current_user = current_user

    # 住所とサブ住所のデータを取得し、インスタンスに格納する
    if current_user.present?
      @address = {
        postal_code: current_user.postal_code,
        address1: current_user.address1,
        address2: current_user.address2
      }

      # テキスト化して結合
      @address[:text] = "#{@address[:postal_code]}, #{@address[:address1]}, #{@address[:address2]}"
    end

    if current_user.secondaddress.present?
      @second_address = {
        second_postal_code: current_user.secondaddress.second_postal_code,
        second_address1: current_user.secondaddress.second_address1,
        second_address2: current_user.secondaddress.second_address2
      }

      # テキスト化して結合
      @second_address[:text] = "#{@second_address[:second_postal_code]}, #{@second_address[:second_address1]}, #{@second_address[:second_address2]}"
    end

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.seller_id = current_user.id
    if @item.image.attached?
      @item.save!
      # チャットルームの作成
      @chat = Chat.create(item: @item)
      redirect_to root_path
    else
      flash.now[:notice] = "画像を添付してください"
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
    @current_user = current_user
  end

  def update
    #itemのidを取得
    @item = Item.find(params[:id])

    #itemの情報を更新
    if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました。"
      redirect_to edit_item_path(@item.id)
    else
      flash[:notice] = "商品情報の更新に失敗しました。"
      render :edit
    end


  end

  def destroy
  end

  def cheackout
    @item = Item.find(params[:item_id])
    @item.update(buyer_id: current_user.id)

    #洗濯した住所のデータを格納する。
    selected_address = params[:selected_address]
    @item.update(address: selected_address)
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :image_meta_data)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    #パラメーターを取得
    @chat = Chat.find(params[:chat_id])
    #パラメーターを取得
    @comment = Message.new(comment_params)
    # @comment = @chat.comment.build(comment_params)
    #@commentに値が入ったらsaveする。できなければリダイレクトをして
    if @comment.nil?
      redirect_to item_path(@chat.item_id)
    else
      @comment.save
      redirect_to item_path(@chat.item.id)
    end
  end

  private

  def comment_params
    params.permit(:comment, :chat_id).merge(user_id: current_user.id)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def show
    @current_user = current_user
  end

  #購入済み商品一覧を表示する機能
  def purchased_items
    @purchase_items = Item.where(buyer_id: current_user.id)
  end

  #出品商品一覧を表示する機能
  def listed_items
    @listed_items = Item.where(seller_id: current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #userのidとパスワードを格納する
    user = User.find_by(name: params[:name])
    #userとパスワードが一致するか確認
    if user && user.authenticate(params[:password])
      #セッションIDを払い出す
      session[:user_id] = user.id
      #ログインしましたとアナウンス
      flash[:notice] = "ログインしました"
      #もし一致する場合にはroot_pathへ移動
      redirect_to items_path(user_id: user.id)
    else
      #ログインできませんでしたとアナウンス
      flash[:notice] = "ユーザー名かパスワードのどちらかが違います。"
      #合わない場合にはsessions#newへ戻る
      render 'new'
    end
  end

  def destroy
    #セッションIDを処分
    session[:user_id] = nil
    #ログでsessions_idがnilになったか確認するためにコード
    Rails.logger.debug "session[:user_id] = #{session[:user_id]}"
    #セッションの完全な処理
    reset_session
    #sessions#newへ戻る
    redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/secondaddresses_helper.rb
module SecondaddressesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/items/cheackout.html.erb
<h1>最終確認画面です。</h1>

<%= form_tag(item_cheackout_path, method: :get) do %>
  <%= hidden_field_tag :item_id, @item.id %>
  <div class="field">
    <%= image_tag(@item.image.variant(resize_to_limit: [500, 500])) %>
  </div>

  <div class="field">
    <p>商品名：<%= @item.name %></P>
  </div>

  <div class="field">
    <p>詳細:<%= @item.explanation %></P>
  </div>

  <div class="field">
    <p>金額：<%= @item.price %>円</P>
  </div>

  <div class="field">
    <p>配送先：<%= @item.address %>への配送をします。</P>
  </div>

<% end %>

<%= form_tag(root_path, method: :get) do %>
  <%= hidden_field_tag 'item[buyer_id]', @current_user.id %>
  <%= submit_tag '購入する（最終確認です。キャンセルは不可です。）' %>
<% end %>

app/views/items/edit.html.erb
<h1>出品商品の編集</h1>

<%= render 'shared/flash_notice' %>

<button><%= link_to '戻る', listed_items_mypage_path(id: @item.id) %></button>

<%= form_for @item, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :商品名 %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div> 

  <div class="field">
    <%= f.label :詳細 %><br />
    <%= f.text_field :explanation, autofocus: true, autocomplete: "explanation" %>
  </div>

  <div class="field">
    <%= f.label :金額 %><br />
    <%= f.number_field :price, autofocus: true, autocomplete: "price" %>
  </div>

  <div class="field">
    <%= f.label :商品写真をアップしてください %><br />
    <%= f.file_field :image, autofocus: true, autocomplete: "image" %>
  </div>

  <div class="actions">
    <%= f.submit "更新する" %>
  </div>
<% end %>

app/views/items/index.html.erb
<% if !current_page?(new_user_session_path) %>
<nav class="navbar">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link"><%= link_to "マイページ", mypage_path(@current_user.id) %></a>
    </li>
  </ul>
</nav>
<% end %>

<h1>商品一覧</h1>

<%= render 'shared/flash_notice' %>

<% @items.each do |item| %>
  <%= render partial: 'shared/item_with_image_link', locals: { item: item } %>
<% end %>

<div class="button-container">
  <button><%= link_to "出品する", "/items/new" %></button>
</div>

app/views/items/new.html.erb
<h1>出品したい商品の情報を入力してください。</h1>

<%= render 'shared/flash_notice' %>

<button><%= link_to "戻る", request.referer || root_path %></button>

<%= form_for @item, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :商品名 %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :詳細 %><br />
    <%= f.text_field :explanation, autofocus: true, autocomplete: "explanation" %>
  </div>

  <div class="field">
    <%= f.label :金額 %><br />
    <%= f.number_field :price, autofocus: true, autocomplete: "price" %>
  </div>

  <div class="field">
    <%= f.label :商品写真をアップしてください %><br />
    <%= f.file_field :image, autofocus: true, autocomplete: "image" %>
  </div>

  <div class="actions">
    <%= f.submit "出品する" %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1>商品の詳細画面になります。</h1>

<% if @item.buyer_id.present? %>
  <button><%= link_to "戻る", purchased_items_mypage_path %></button>
<% else %>
  <button><%= link_to "戻る", root_path %></button>
<% end %>

<%= form_tag(item_cheackout_path, method: :get) do %>
  <%= hidden_field_tag :item_id, @item.id %>
  <div class="field">
    <%= image_tag(@item.image.variant(resize_to_limit: [500, 500])) %>
  </div>

  <div class="field">
    <p>商品名：<%= @item.name %></P>
  </div>

  <div class="field">
    <p>詳細:<%= @item.explanation %></P>
  </div>

  <div class="field">
    <p>金額：<%= @item.price %>円</P>
  </div>

<% end %>

<% if @item.buyer_id.present? %>
  <p>購入済み商品です。</p>
<% else %>
  <h3>チャット</h3>
  <div class="posts">
    <% if @chat.messages.blank? %>
      <p>コメントはありません</p>
    <% else %>
      <% @chat.messages.each do |message| %>
        <p><%= message.user.name %>: <%= message.comment %></p>
      <% end %>
    <% end %>
  </div>



  <div class="posts">
    <%= form_with(url: messages_path, method: :post) do |form| %>

      <%= form.hidden_field :chat_id, value: @chat.id %>
      <%= form.hidden_field :user_id, value: @current_user.id %>

      <%= form.text_field :comment %>
      <%= form.submit "送信" %>
    <% end %>
  </div>

  <% if @item.seller_id.to_i == @current_user.id %>
    <p><%= @current_user.name %>様が出品している商品です。</p>
    <%= link_to "商品を編集する", edit_item_path %>
  <% else %>
    <%= form_tag(item_cheackout_path(@item), method: :get) do %>
      <%= hidden_field_tag :item_id, @item.id %>

      <% if @address.present? %>
        <h3>住所</h3>
        <% address_text = "#{@address[:postal_code]} #{@address[:address1]} #{@address[:address2]}" %>
        <p><%= address_text %></p>
        <%= radio_button_tag 'selected_address', address_text %>
        この住所を選択する
      <% end %>

      <% if @second_address.present? %>
        <h3>サブ住所</h3>
        <% second_address_text = "#{@second_address[:second_postal_code]} #{@second_address[:second_address1]} #{@second_address[:second_address2]}" %>
        <p><%= second_address_text %></p>
        <%= radio_button_tag 'selected_address', second_address_text %>
        このサブ住所を選択する
      <% end %>

      <br /><br />
      <%= submit_tag '購入する' %>
    <% end %>
  <% end %>
<% end %>

app/views/mypages/listed_items.html.erb
<h1>出品商品一覧</h1>
<button><%= link_to "戻る", mypage_path %></button>

<% if @listed_items.present? %>
  <% @listed_items.each do |item| %>
    <%= render partial: 'shared/item_with_image_link', locals: { item: item } %>
  <% end %>
<% else %>
  <p>出品商品はありません</p>
<% end %>

app/views/mypages/purchased_items.html.erb
<h1>購入済み商品一覧</h1>
<button><%= link_to "戻る", mypage_path %></button>

<% if @purchase_items.present? %>
  <% @purchase_items.each do |item| %>
    <%= render partial: 'shared/item_with_image_link', locals: { item: item } %>
  <% end %>
<% else %>
  <p>購入済み商品はありません</p>
<% end %>

app/views/mypages/show.html.erb
<h1>マイページ</h1>
<button><%= link_to "戻る", root_path %></button>
<nav class="mypage_navbar">
  <ul class="mypage_navbar-nav">
    <li class="mypage_nav-item">
      <a class="nav-link"><%= link_to "ログアウト", destroy_user_session_path %></a>
    </li>
    <li class="mypage_nav-item">
      <a class="nav-link"><%= link_to "購入済み商品一覧", purchased_items_mypage_path %></a>
    </li>
    <li class="mypage_nav-item">
      <a class="nav-link"><%= link_to "出品商品一覧", listed_items_mypage_path %></a>
    </li>
    <li class="mypage_nav-item">
      <a class="nav-link"><%= link_to "サブ住所編集", edit_or_new_secondaddress_path %></a>
    </li>
    <li class="mypage_nav-item">
      <a class="nav-link"><%= link_to "ユーザー情報編集", edit_user_registration_path %></a>
    </li>
  </ul>
</nav>